Name:           ros-melodic-cob-description
Version:        0.6.10
Release:        0%{?dist}
Summary:        ROS cob_description package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/cob_description
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-gazebo-ros
Requires:       ros-melodic-rosbash
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rosunit
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin

%description
This package contains the description (mechanical, kinematic, visual, etc.) of
the Care-O-bot robot. The files in this package are parsed and used by a variety
of other components. Most users will not interact directly with this package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Mar 14 2019 Felix Messmer <felixmessmer@gmail.com> - 0.6.10-0
- Autogenerated by Bloom

