Name:           ros-melodic-cob-common
Version:        0.7.0
Release:        1%{?dist}
Summary:        ROS cob_common package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://ros.org/wiki/cob_common
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-cob-actions
Requires:       ros-melodic-cob-description
Requires:       ros-melodic-cob-msgs
Requires:       ros-melodic-cob-srvs
Requires:       ros-melodic-raw-description
BuildRequires:  ros-melodic-catkin

%description
The cob_common stack hosts common packages that are used within the Care-O-bot
repository. E.g. utility packages or common message and service definitions etc.
Also the urdf desciption of the robot is located in this stack.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Tue Aug 06 2019 Felix Messmer <felixmessmer@gmail.com> - 0.7.0-1
- Autogenerated by Bloom

* Thu Mar 14 2019 Felix Messmer <felixmessmer@gmail.com> - 0.6.10-0
- Autogenerated by Bloom

